---
# - name: "Create ext4 filesystem on {{ instance_store_device }}"
#   filesystem:
#      dev: /dev/xvda2
#      fstype: ext3

- name: "Directories Exists"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ s3ql_user }}"
    group: "{{ s3ql_group }}"
    mode: 0775
  with_items:
     - "{{ s3ql_cache_path }}"
     - "{{ s3ql_log_root }}"
  tags:
    - directory-structure

- name: "Directory Exists {{ s3ql_mountpoint }}"
  file:
    state: directory
    path: "{{ s3ql_mountpoint }}"
    owner: "{{ s3ql_user }}"
    group: "{{ s3ql_group }}"
    mode: 0775
  ignore_errors: True
  tags:
    - directory-structure

- name: "Upload Config"
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0400
    owner: "{{ s3ql_user }}"
    group: "{{ s3ql_group }}"
  with_items:
    - data/www/s3ql-authinfo
    - etc/init/s3ql.conf
  tags:
    - configuration
    - template-configuration

- name: "Create s3ql filesystem on {{ s3ql_bucket_name }}"
  command: "mkfs.s3ql s3://{{ s3ql_bucket_name }} --plain --cachedir={{ s3ql_cache_path }} --authfile={{ s3ql_authinfo_path }}"
  ignore_errors: True

- name: "Mount {{ s3ql_bucket_name }} to {{ s3ql_mountpoint }}"
  service:
    name: s3ql
    state: started
  tags:
    - mount-volume
