---
# - name: "Create ext4 filesystem on {{ instance_store_device }}"
#   filesystem:
#      dev: /dev/xvda2
#      fstype: ext3

- name: "Directories Exists"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ s3ql_user }}"
    group: "{{ s3ql_group }}"
    mode: 0775
  with_items:
     - "{{ s3ql_mountpoint }}"
     - "{{ s3ql_cache_path }}"
  tags:
    - directory-structure

- name: "Upload Config"
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0400
    owner: "{{ s3ql_user }}"
    group: "{{ s3ql_group }}"
  with_items:
    - data/www/s3ql-authinfo
    - etc/init/s3ql.conf
  tags:
    - configuration
    - template-configuration

- name: "Mount {{ s3ql_bucket_name }} to {{ s3ql_mountpoint }}"
  mount:
    state: mounted
    src: "s3://{{ s3ql_bucket_name }}"
    fstype: s3ql
    name: "{{ s3ql_mountpoint }}"
  tags:
    - mount-volume
