---
- name: Create cache directory
  file:
    state: directory
    path: "{{ s3ql_cache_dir }}"
    owner: "{{ s3ql_user }}"
    group: "{{ s3ql_group }}"
    mode: 0775
  tags:
    - directory-structure

- name: Configure | /etc/fuse.conf | user_allow_other
  lineinfile:
    state: present
    dest: /etc/fuse.conf
    regexp: '^#?user_allow_other'
    line: user_allow_other
  tags:
    - configuration
    - fuse

- name: Create a mountpoint directory
  file:
    state: directory
    path: "{{ s3ql_mountpoint }}"
    owner: "{{ s3ql_user }}"
    group: "{{ s3ql_group }}"
    mode: 0775
  ignore_errors: True
  tags:
    - directory-structure

- name: Upload Authinfo from template
  template:
    src: s3ql-authinfo.j2
    dest: "{{ s3ql_authinfo_file }}"
    mode: 0400
    owner: "{{ s3ql_user }}"
    group: "{{ s3ql_group }}"
  tags:
    - configuration
    - template-configuration

- name: Upload S3QL makefs expect-script from template
  template: 
    src: s3ql_makefs.expect.j2
    dest: /usr/local/bin/s3ql_makefs.expect
    mode: 0700
  tags:
    - configuration
    - template-configuration

# This won't run if .initialized file exists, so result.changed will be false,
# thereby suppressing other install tasks.  Install file is created by the
# "Mark s3ql install as initialized" task.
- name: Check for existing initialized S3QL install
  command: true
           creates=/etc/.s3ql.initialized
  register: result

- name: Make S3QL filesystem (run only once)
  shell: /usr/local/bin/s3ql_makefs.expect
  when: result|changed

- name: Mark S3QL install as initialized
  command: touch /etc/.s3ql.initialized
  args:
    creates: /etc/.s3ql.initialized
  when: result|changed

- name: Upload S3QL systemd unit file from template
  template: 
    src: s3ql.service.j2
    dest: /etc/systemd/system/s3ql.service
  notify:
  - reload systemd
  - restart s3ql
  tags:
    - configuration
    - template-configuration

- name: Enable S3QL service and mount
  service: 
    name: s3ql.service
    enabled: yes 
    state: started
  tags:
  - mount-volume
