---
- include_tasks: install-on-alpine.yml
  when: ansible_os_family == "Alpine"

- include_tasks: install-on-debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: configure.yml

- include_tasks: start-systemd.yml
  when: ansible_os_family == "Debian"

- name: Check, that s3ql filesystem is really mounted.
  command: grep -qs "{{ s3ql_mountpoint }} " /proc/mounts
  #command: mountpoint -q "{{ s3ql_mountpoint }}"
  changed_when: False
  when: not travis_testing
