---
- include_tasks install-alpine.yml
  when: ansible_distribution == "Alpine"

- include_tasks: install-debian.yml
  when: ansible_distribution == "Debian"

- include_tasks: configure.yml

- name: Check, that s3ql filesystem is really mounted.
  command: grep -qs "{{ s3ql_mountpoint }} " /proc/mounts
  #command: mountpoint -q "{{ s3ql_mountpoint }}"
  changed_when: False

# In case the role is called more than once in one play:
- meta: flush_handlers
