---
- include_tasks: install-on-alpine.yml
  when: ansible_os_family == "Alpine"

- include_tasks: install-on-debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: configure.yml

# In case the role is called more than once in one play:
- meta: flush_handlers

- name: Check, that s3ql filesystem is really mounted.
  command: grep -qs "{{ s3ql_mountpoint }} " /proc/mounts
  #command: mountpoint -q "{{ s3ql_mountpoint }}"
  changed_when: False
