---

- name: Upload S3QL systemd unit file from template.
  template:
    src: s3ql.service.j2
    dest: /etc/systemd/system/s3ql-{{ s3ql_prefix }}.service
  register: s3ql_servicefile

- name: Issue daemon-reload to pick up config changes.
  systemd:
    daemon_reload: yes
    name: s3ql-{{ s3ql_prefix }}.service
  when: s3ql_servicefile.changed

- name: Enable S3QL service and mount.
  systemd:
    name: s3ql-{{ s3ql_prefix }}.service
    enabled: True
    state: started
  register: s3ql_service_mount
  when: not travis_testing

- name: Pause for a few seconds to complete mounting.
  pause:
    seconds: 3
  when: s3ql_service_mount.changed
